### ISSUE TITLE
Memory leak due to Arc cycles

### ISSUE THREAD

**Issue by TheButlah** [Finomnis/tokio-graceful-shutdown#19]
Hi, I've been reading through the codebase. It looks like `SubsystemDescriptor`s hold `Arc<SubsystemData>`. And the `SubsystemData` holds the subsystem descriptors (without an `Arc`). Doesn't this mean that even if the parent subsystem is dropped, there will be a cyclic reference between a `SubsystemDescriptor` and a `SubsystemData`? So neither gets dropped and the memory is leaked

**Comment by Finomnis** [comment]
No problem, thanks for reporting anyway :)

I run a full LLVM leak detection in the CI to catch those corner cases, and so far they didn't complain :)

Working on a full rewrite though, that (hopefully) will make the code structure a little clearer and more extensible.
