### ISSUE TITLE
macOS support?

### ISSUE THREAD

**Issue by beeb** [Finomnis/tokio-graceful-shutdown#43]
I'm trying to run the code examples on macOS but the program just hangs without any error indefinitely.

```
$ git clone git@github.com:Finomnis/tokio-graceful-shutdown.git
$ cd tokio-graceful-shutdown
$ cargo run --example 01_normal_shutdown
# builds successfully, then launches and hangs
```

```
$ rustc --version
rustc 1.64.0 (a55dd71d5 2022-09-19)
$ cargo --version
cargo 1.64.0 (387270bc7 2022-09-16)
```

macOS 12.5 (21G72)

**Comment by beeb** [comment]
I had my logging disabled through environment variables

**Comment by Finomnis** [comment]
This example is supposed to wait for Ctrl-C :) does it react to that?

**Comment by Finomnis** [comment]
Ah never mind :) does it work for you now?

**Comment by beeb** [comment]
Yes it works! My bad, end of the day and my brain was fried

**Comment by Finomnis** [comment]
Nice :) have fun

**Comment by beeb** [comment]
Thanks for this great lib!
