### ISSUE TITLE
Sequential shutting down of subsystems after SIGINT/SIGTERM received 

### ISSUE THREAD

**Issue by kurotych** [Finomnis/tokio-graceful-shutdown#80]
Hello, thanks for your library.

I want to implement controlled sequential shutting down of subsystems.
As an example, I took [13_partial_shutdown.rs](https://github.com/Finomnis/tokio-graceful-shutdown/blob/main/examples/13_partial_shutdown.rs) and made one "main" subsystem that has 3 (for example) its subsystems 

But It figured out when I shut down my service with several subsystems by Ctrl + C all `on_shutdown_requested()` callbacks of all subsystems called. 

```rust
tokio::select! {
    _ = subsys.on_shutdown_requested() => {
        info!("Nested subsystem shutdown");
        return Ok(())
    }
    ....
}
```

Is there a way to block `on_shutdown_requested` for the nested subsystem until I initiate it from parent one as in the example? 

Now I see the only way is to remove `on_shutdown_requested` from the nested subsystem, add an additional "shutdown" channel, and trigger them from the parent.  But it would be nice to have such functionality in this library. 

What do you think?

**Comment by Finomnis** [comment]
How about this? (#82)

I added a `.finished()` method to `NestedSubsystem` and added an example on how it could be used to achieve sequential shutdown.

**Comment by Finomnis** [comment]
Does this work for your usecase? I'll release it as soon as you confirm that this is what you need.

**Comment by Finomnis** [comment]
> Now I see the only way is to remove `on_shutdown_requested` from the nested subsystem, add an additional "shutdown" channel, and trigger them from the parent. But it would be nice to have such functionality in this library.

I don't actually think this is such a bad way to deal with this. I don't think this crate could add anything that would make this situation substantially easier; adding such a functionality would just bloat the API. I'll add an example for a shutdown orchestrated by a parent.

**Comment by kurotych** [comment]
> Turns out it wasn't hard at all, and also didn't clutter the API.
> 
> Here you go. Is this what you had in mind? https://github.com/Finomnis/tokio-graceful-shutdown/blob/121414f4204a72ab0ac13d199596ad0c64bc0fd9/examples/20_orchestrated_shutdown_order.rs

Hi @Finomnis. Yes, this is exactly what I need, thank you!

**Comment by Finomnis** [comment]
Glad I could help :)
