### ISSUE TITLE
Add inter-subsystem communication channels.

### ISSUE THREAD

**Issue by hirschenberger** [Finomnis/tokio-graceful-shutdown#88]
I like this crate not only for the graceful shutdown functionality, also the nested subsystems structure and encapsulate the parts of a bigger app pretty well and help with reuse and clarity.

I often create a set of subsystems that have to communicate with each other by creating the structs and wiring up mpsc and broadcast channels between them.

(A nice rule I found is: If a subsystem has a tx and rx to the same subsystem, make it a child subsystem.)

It would be nice if subsystems would have built-in channel communication. So you could just pass a Subsystem-Handle to another Subsystem to make them communicate.

It would even be nice, if there was a global registy, where I could send a message by using the name of a subsystem.

I know, you would ask why not just use an Actor-System, but I like the static structure and hard-wired communication.

There's a crate [orchestra](https://crates.io/crates/orchestra) that is doing it like this, but I found it too complicated to use and didn't like that excessive use of proc-macros.

**Comment by Finomnis** [comment]
Thanks it your idea :)

I'm trying to keep this crate as simple as possible though, I'm trying to prevent feature creep and bloat. And I'm afraid that functionality is out of scope for what I'm trying to achieve :/

You can always pass any kind of arguments into subsystems, so you could use whatever fifo/messagequeue/pipe create of your choice to achieve this on a higher layer on top of this crate.

**Comment by hirschenberger** [comment]
No Problem. It was just an idea and I'd keep passing channels into subsystems with structs.
