### ISSUE TITLE
The problem of Edition 2021

### ISSUE THREAD

**Issue by CHCP** [Finomnis/tokio-graceful-shutdown#9]
Hi @Finomnis 
  Thanks for your work on  this crates tokio-graceful-shutdown.

If you can modify the Edition to 2018, it may be used in a wider range. After all, there are many programs that cannot use Edition 2021 temporarily, so would you like to change Edition to 2018?  

Thanks again.

**Comment by Finomnis** [comment]
Your reasoning is sound and I don't see anything that would disagree with your statement.
